import type { AnalysisResult, Language } from '../types.js';

function escapeLabel(value: string): string {
  return value
    .replaceAll('\\', '/')
    .replaceAll('\r', ' ')
    .replaceAll('\n', ' ')
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;');
}

const CLASS_BY_LANGUAGE: Record<Language, string> = {
  javascript: 'javascript',
  typescript: 'typescript',
  python: 'python',
  go: 'go',
};

export function renderMermaid(result: AnalysisResult): string {
  const nodeIds = new Map(result.nodes.map((node, index) => [node.id, `N${index}`]));
  const lines = [
    '%% Generated by ArchLens — https://github.com/mockingbird777/archlens',
    `%% ${result.summary.files} files · ${result.summary.dependencies} dependencies · ${result.summary.cycles} cycles`,
    'flowchart LR',
  ];
  for (const node of result.nodes) {
    const mermaidId = nodeIds.get(node.id);
    if (!mermaidId) continue;
    lines.push(`  ${mermaidId}["${escapeLabel(node.id)}"]:::${CLASS_BY_LANGUAGE[node.language]}`);
  }
  for (const edge of result.edges) {
    const source = nodeIds.get(edge.source);
    const target = nodeIds.get(edge.target);
    if (source && target) lines.push(`  ${source} -->|"${escapeLabel(edge.specifier)}"| ${target}`);
  }
  const cycleNodes = result.nodes.filter((node) => node.cycleIds.length > 0).map((node) => nodeIds.get(node.id)).filter(Boolean);
  if (cycleNodes.length > 0) lines.push(`  class ${cycleNodes.join(',')} cycle`);
  lines.push(
    '  classDef javascript fill:#f7df1e22,stroke:#f7df1e,color:#e8e8e8;',
    '  classDef typescript fill:#3178c622,stroke:#5ea7e0,color:#e8e8e8;',
    '  classDef python fill:#3776ab22,stroke:#ffd343,color:#e8e8e8;',
    '  classDef go fill:#00add822,stroke:#5dc9e2,color:#e8e8e8;',
    '  classDef cycle stroke:#ff5d7d,stroke-width:3px;',
  );
  return `${lines.join('\n')}\n`;
}
